# Using main requires flex. gcloud app deploy might incur costs.
# flex does not provide instance number value as std does.
runtime: go
env: flex

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

skip_files:
- ^\.git/.*$
- ^.*_test.go$
- ^.*.yaml$
